name: pr / all

on: 
  pull_request:
    branches:
    - master
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
