name: "build-test"
on: # rebuild any PRs
  pull_request:
    branches:
    - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        github_action: repository_dispatch
        github_event_type: test_event
        github_client_payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'