name: release / notification

on:
  release:
    types: [ published ]

jobs:
  repository_dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: know-ops/git-actions@v0.0.1
        with:
          git_action: files_changed
          git_created: "true"
          git_modified: "true"
          git_deleted: "true"